services:
  dummy-service:
    build: .
    container_name: dummy-backend
    restart: always
    ports:
      - "8000:8000" # Expose API on Port 8000
    networks:
      - dummy-network
    volumes:
      - ./data:/app/data

networks:
  dummy-network:
    external: true
